### ISSUE TITLE
'Unresolved external symbol' (LNK2019) when building on Windows with Visual Studio

### ISSUE THREAD

**Issue by SalatielSauer** [Big-Onche/Tesseract-Sauerbraten#13]
Hi, any recommendations for building the project on Windows 10?
Some LNK errors occur when I try using Visual Studio 2022:

![image](https://github.com/Big-Onche/Tesseract-Sauerbraten/assets/9287152/dc840549-90a9-4119-ae52-0079a90cc1f0)
![image](https://github.com/Big-Onche/Tesseract-Sauerbraten/assets/9287152/b5cfe127-4da7-4060-acd3-449985e68b7f)

**Comment by Big-Onche** [comment]
I use code::blocks on windows, so I don't have updated the VS project. I need to add all source and header files related to Sauerbraten (monsters.cpp, etc.) in the VS project and also in the makefile btw.

**Comment by SalatielSauer** [comment]
> Hello, I use code::blocks on windows, so I don't have updated the VS project. I need to add all source and header files related to Sauerbraten (monsters.cpp, etc.) in the VS project and also in the makefile btw.

Thanks, for now adding the occurrences of 'monster' and 'movable' to the [makefile](https://github.com/SalatielSauer/Tesseract-Sauerbraten/commit/4d20d90e2f7bad26f322cbe012d07cb5a44826c6) worked with mingw32-make.

**Comment by Big-Onche** [comment]
Thanks for the makefile!

I just updated the Visual Studio project, now it works https://github.com/Big-Onche/Tesseract-Sauerbraten/commit/2d718da5ea4bdd4212889a432850666825f50bb5
